import {StyleSheet} from 'react-native';
import {px2dp, scaleHeight, setSpText} from '@/ui/utils/screenUtil';

export const styles = StyleSheet.create({
  totalcontainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: scaleHeight(32),
    marginTop: scaleHeight(32),
  },
  total_content: {
    width: px2dp(686),
    height: scaleHeight(160),
    backgroundColor: '#FFFFFF',
    shadowOffset: {width: px2dp(4), height: scaleHeight(5)},
    shadowOpacity: 0.1,
    shadowRadius: px2dp(5),
    shadowColor: '#000000',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: px2dp(12),
    paddingVertical: scaleHeight(26),
  },
  total_item: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  total_item_left: {
    width: px2dp(300),
    fontSize: setSpText(28),
    color: 'rgba(123,135,150,1)',
    marginLeft: px2dp(32),
  },
  total_item_right: {
    flex: 1,
    flexGrow: 1,
    fontSize: setSpText(28),
    textAlign: 'right',
    color: 'rgba(51,51,51,1)',
    marginRight: px2dp(32),
  },
  container: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemcontainer: {
    width: px2dp(686),
    marginBottom: scaleHeight(24),
    backgroundColor: '#FFF',
    borderRadius: 8,
  },
  exclusive_header: {
    width: '100%',
    height: scaleHeight(112),
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#2d8dbc',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  exclusive_header_title: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: setSpText(50),
    fontWeight: 'bold',
    marginLeft: px2dp(40),
  },
  header: {
    height: scaleHeight(142),
    padding: 10,
    borderColor: '#ECECEC',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  header_left: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header_img: {
    width: px2dp(80),
    height: px2dp(80),
  },
  header_right: {
    height: '100%',
    flex: 5,
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  header_right_id: {
    width: '60%',
    fontSize: setSpText(32, true),
    color: 'rgba(51,51,51,1)',
  },
  header_right_date: {
    width: '40%',
    textAlign: 'right',
    fontSize: setSpText(28),
    color: 'rgba(156,165,177,1)',
  },
  header_right_status: {
    width: '60%',
    fontSize: setSpText(28, true),
    color: '#6ABF47',
    fontWeight: '500',
  },
  header_item_time: {
    width: '40%',
    justifyContent: 'flex-end',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  bold: {
    fontWeight: 'bold',
  },
  header_right_time: {
    flex: 1,
    textAlign: 'right',
    fontSize: setSpText(28),
    color: 'rgba(156,165,177,1)',
  },
  header_right_alert: {
    width: px2dp(186),
    height: scaleHeight(40),
    borderRadius: px2dp(50),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  header_right_alert_text: {
    fontSize: setSpText(26),
    textAlign: 'right',
  },
  emptycontainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  empty_text: {
    fontSize: setSpText(32),
    color: 'rgba(156,165,177,1)',
    marginTop: scaleHeight(450),
  },
  sync: {
    height: scaleHeight(41),
    backgroundColor: '#EBF6FF',
    borderRadius: px2dp(8),
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: px2dp(2),
    paddingRight: px2dp(14),
    marginRight: px2dp(30),
  },
  sync_icon: {
    height: px2dp(32),
    width: px2dp(32),
  },
  sync_text: {
    color: '#0091FF',
    fontSize: setSpText(24),
    marginLeft: px2dp(12),
  },
  picker: {
    height: scaleHeight(48),
    width: px2dp(128),
    backgroundColor: 'rgba(235, 246, 255, 1)',
    borderRadius: px2dp(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: px2dp(30),
  },
  picker_text: {
    color: 'rgba(0, 145, 255, 1)',
    fontSize: setSpText(26),
  },
  footer: {
    width: '100%',
    paddingTop: '1%',
    paddingBottom: '3%',
    borderColor: '#ECECEC',
    borderTopColor: '#ECECEC',
    borderTopWidth: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  footer_icon: {
    flex: 0,
    width: px2dp(48),
    height: undefined,
    aspectRatio: 1,
    marginLeft: px2dp(32),
  },
  footer_location: {
    flex: 1,
    color: '#999999',
    fontSize: setSpText(26),
    marginLeft: px2dp(15),
  },
  footer_distance: {
    flex: 0,
    color: '#999999',
    fontSize: setSpText(26),
    marginRight: px2dp(15),
    width: px2dp(150),
    textAlign: 'center',
  },
  checkbox_container: {
    padding: 0,
    margin: 0,
    paddingRight: px2dp(10),
  },
  checkbox_icon: {
    width: px2dp(48),
    height: undefined,
    aspectRatio: 1,
  },
});
