import {StyleSheet} from 'react-native';
import {screenW, scaleHeight, setSpText, px2dp} from '@/ui/utils/screenUtil';

export const styles = StyleSheet.create({
  badge: {
    width: 15,
    height: 15,
    borderRadius: 50,
  },
  content: {
    // height: '89.28%',
    // height: '80.58%',
    height: '100%',
    // height:scaleHeight(1375),
    width: '100%',
    flexGrow: 1,
    flexShrink: 1,
    position: 'relative',
    display: 'flex',
  },
  header: {
    width: screenW,
    display: 'flex',
    flexDirection: 'row',
    height: scaleHeight(100),
    borderTopWidth: 1,
    borderTopColor: '#ECECEC',
    backgroundColor: '#FFFFFF',
    justifyContent: 'space-around',
    // shadowOffset: {width: px2dp(4), height: px2dp(5)},
    // shadowOpacity: 0.15,
    // shadowRadius: px2dp(10),
    // marginBottom: scaleHeight(24),
  },
  header_menu: {
    // height: '100%',
    // width: screenW / 3,
    display: 'flex',
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header_menu_text: {
    color: '#999999',
    fontSize: setSpText(28),
    fontWeight: '500',
  },
  header_menu_text_active: {
    fontSize: setSpText(32),
    color: 'rgba(45,141,188,1)',
  },
  body: {
    flex: 1,
    display: 'flex',
  },
  body_container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: screenW,
    backgroundColor: '#F2F2F2',
    // paddingBottom: scaleHeight(150),
    paddingHorizontal: px2dp(32),
  },
  filtercontainer: {
    height: scaleHeight(124),
    // marginVertical: scaleHeight(32),
    backgroundColor: '#F2F2F2',
  },
  filter_item: {
    height: '100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  filter_item_text: {
    height: scaleHeight(60),
    // width: px2dp(148),
    backgroundColor: '#DBE8EE',
    borderRadius: px2dp(30),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: px2dp(24),
    position: 'relative',
  },
  selected_filter_item_text: {
    backgroundColor: '#2D8DBC',
  },
  work_order_list: {
    flex: 1,
    backgroundColor: '#F2F2F2',
    paddingBottom: scaleHeight(200),
    marginBottom: scaleHeight(100),
  },
  filter_item_text_content: {
    color: 'rgba(45, 141, 188, 1)',
    fontSize: setSpText(32),
    paddingHorizontal: px2dp(32),
  },
  selected_filter_item_text_content: {
    color: 'rgba(255, 255, 255, 1)',
  },
  filter_item_bage: {
    position: 'absolute',
    right: px2dp(-5),
    top: scaleHeight(25),
  },
  emptycontainer: {
    // width:screenW,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    // justifyContent: 'center',
    alignItems: 'center',
    marginTop: scaleHeight(336),
  },
  empty_img: {
    width: px2dp(272),
    height: scaleHeight(212),
  },
  empty_text: {
    fontSize: setSpText(28),
    color: '#9CA5B1',
    marginTop: scaleHeight(60),
  },
  totalcontainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: scaleHeight(32),
    marginTop: scaleHeight(32),
  },
  total_content: {
    width: px2dp(686),
    height: scaleHeight(160),
    backgroundColor: '#FFFFFF',
    shadowOffset: {width: px2dp(4), height: scaleHeight(5)},
    shadowOpacity: 0.1,
    shadowRadius: px2dp(5),
    shadowColor: '#000000',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: px2dp(12),
    paddingVertical: scaleHeight(26),
  },
  total_item: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  total_item_left: {
    width: px2dp(300),
    fontSize: setSpText(28),
    color: 'rgba(123,135,150,1)',
    marginLeft: px2dp(32),
  },
  total_item_right: {
    flex: 1,
    flexGrow: 1,
    fontSize: setSpText(28),
    textAlign: 'right',
    color: 'rgba(51,51,51,1)',
    marginRight: px2dp(32),
  },
  tooltip: {
    width: '100%',
    backgroundColor: '#F2F2F2',
  },
  tooltip_text: {
    fontSize: setSpText(28),
    color: 'rgba(153,153,153,1)',
    marginLeft: px2dp(32),
  },
  resequence_container: {
    position: 'absolute',
    right: 0,
    top: scaleHeight(1200),
  },
  resequence_Linear: {
    width: px2dp(300),
    height: scaleHeight(96),
    borderTopLeftRadius: 500,
    borderBottomLeftRadius: 500,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resequence_title: {
    fontSize: setSpText(32),
    color: '#fff',
    fontWeight: '500',
  },
  resequence_content: {
    fontSize: setSpText(24),
    color: '#fff',
    textAlign: 'center',
  },
});
