import {StyleSheet} from 'react-native';
import {screenW, scaleHeight, setSpText, px2dp} from '@/ui/utils/screenUtil';

export const styles = StyleSheet.create({
  iconStyle: {
    fontSize: setSpText(28),
  },
  containerStyle: {flex: 1},
  safeAareaStyle: {
    flex: 1,
    display: 'flex',
  },
  content: {
    flex: 1,
    width: '100%',
    position: 'relative',
    backgroundColor: '#F2F2F2',
    borderTopWidth: 1,
    borderTopColor: '#ECECEC',
  },
  homeContainer: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },
  homeHeader: {
    display: 'flex',
    flexDirection: 'column',
    width: screenW,
    position: 'relative',
    height: scaleHeight(260),
    marginTop: scaleHeight(20),
    zIndex: 1,
  },
  homeHeader_content: {
    flex: 1,
  },
  homeHeader_content_name: {
    fontSize: setSpText(36),
    color: 'rgba(255,255,255,1)',
    width: px2dp(500), //342
    lineHeight: scaleHeight(44),
    marginLeft: px2dp(48),
    marginTop: scaleHeight(30),
  },
  homeHeader_content_location: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: px2dp(48),
    marginTop: scaleHeight(30),
  },
  homeHeader_content_location_text: {
    fontSize: setSpText(26),
    color: 'rgba(255,255,255,1)',
    marginLeft: px2dp(16),
    width: px2dp(600),
  },
  nav_icon_style: {
    width: px2dp(44),
    height: px2dp(44),
  },
  location_not_found_warning: {
    fontSize: setSpText(26),
    color: 'rgba(255, 170, 0, 1)',
    marginTop: scaleHeight(16),
  },
  homeOrder: {
    height: scaleHeight(350),
    width: screenW,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    position: 'relative',
    zIndex: 99,
  },
  duty_container: {
    height: scaleHeight(400),
    width: px2dp(702),
    backgroundColor: 'rgba(255,255,255,1)',
    display: 'flex',
    alignItems: 'center',
    borderRadius: px2dp(24),
    marginTop: scaleHeight(-80),
  },
  duty_tip: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  duty_tip_round: {
    width: px2dp(8),
    height: undefined,
    aspectRatio: 1,
    backgroundColor: '#3BBCB7',
    borderRadius: px2dp(500),
    marginRight: px2dp(12),
  },
  duty_tip_text: {
    paddingBottom: scaleHeight(10),
    fontSize: setSpText(26),
    color: '#666666',
  },
  duty_accepting_box: {
    backgroundColor: 'white',
    borderColor: 'white',
  },
  duty_accepting_text: {
    fontSize: setSpText(26),
    color: 'rgba(51,51,51,1)',
  },
  duty_button: {
    marginTop: scaleHeight(56),
  },
  duty_button_to: {
    width: scaleHeight(240),
    height: undefined,
    aspectRatio: 1,
    borderRadius: px2dp(500),
    alignItems: 'center',
    justifyContent: 'center',
  },
  duty_button_text: {
    textAlign: 'center',
    fontSize: setSpText(36),
    color: '#FFF',
  },
  duty_button_text_success: {
    textAlign: 'center',
    fontSize: setSpText(36),
    color: 'green',
  },
  duty_button_text_fail: {
    textAlign: 'center',
    fontSize: setSpText(36),
    color: 'red',
  },
  homeOrder_status_container: {
    height: scaleHeight(256),
    width: px2dp(702),
    backgroundColor: 'rgba(255,255,255,1)',
    borderRadius: px2dp(30),
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#CCC',
    shadowOffset: {width: px2dp(0), height: px2dp(-10)},
    shadowOpacity: 0.4,
    shadowRadius: px2dp(10),
    position: 'absolute',
    top: scaleHeight(-80),
    zIndex: 2,
  },
  homeOrder_status_content_header: {
    height: scaleHeight(98),
    borderBottomColor: '#ECECEC',
    borderBottomWidth: 2,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeOrder_status_content_header_title: {
    flex: 1,
    fontSize: setSpText(32),
    color: 'rgba(51,51,51,1)',
    fontWeight: '500',
    marginLeft: px2dp(30),
  },
  homeOrder_status_content_header_price: {
    flex: 1,
    fontSize: setSpText(32),
    color: 'rgba(247,181,0,1)',
    fontWeight: '500',
    textAlign: 'right',
    marginRight: px2dp(30),
  },
  homeOrder_status_content: {
    width: '100%',
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
  },
  homeOrder_status_content_item: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: scaleHeight(52),
    paddingBottom: scaleHeight(52),
  },
  homeOrder_status_content_container: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
  },
  homeOrder_status_content_number: {
    fontSize: setSpText(50),
    fontWeight: '500',
    color: 'rgba(45,141,188,1)',
  },
  homeOrder_status_content_text: {
    fontSize: setSpText(28),
    color: 'rgba(51,51,51,1)',
  },
  workHour: {
    height: scaleHeight(300),
    width: screenW,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#F2F2F2',
    marginBottom: scaleHeight(24),
  },
  workHour_content: {
    height: scaleHeight(300),
    width: px2dp(702),
    backgroundColor: 'rgba(255,255,255,1)',
    borderRadius: px2dp(30),
    shadowColor: 'rgb(0,0,0)',
    shadowOffset: {width: px2dp(20), height: px2dp(4)},
    shadowOpacity: 0.2,
    shadowRadius: px2dp(10),
  },
  workHour_title: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: px2dp(32),
    height: scaleHeight(108),
  },
  workHour_progress: {
    width: '100%',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  workHour_text: {
    fontSize: setSpText(42),
  },
  workHour_progress_content: {
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  startHour: {
    marginRight: px2dp(30),
    fontSize: setSpText(32),
  },
  endHour: {
    marginLeft: px2dp(30),
    fontSize: setSpText(32),
  },

  logincontainer: {
    backgroundColor: 'rgba(255,255,255,1)',
    width: screenW,
    height: scaleHeight(120),
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: scaleHeight(24),
    marginBottom: scaleHeight(40),
  },
  login_button: {
    width: px2dp(690),
    height: scaleHeight(90),
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  login_button_text: {
    fontSize: setSpText(32),
    color: 'rgba(255,255,255,1)',
    fontWeight: '500',
  },
  list_item: {
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  item_title_content: {
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  item_title: {
    fontSize: setSpText(32),
    fontWeight: '500',
    color: '#333333',
    flex: 1,
  },
  item_title_right: {
    flex: 1,
    fontSize: setSpText(28),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    color: '#9CA5B1',
  },
  scrollview_container: {
    marginTop: 10,
  },
});
